export default {
  pages: [
    'pages/component/index',
    'pages/component/pages/view/view',
    'pages/component/pages/scroll-view/scroll-view',
    'pages/component/pages/icon/icon',
    'pages/component/pages/progress/progress',
    'pages/component/pages/image/image',
    'pages/component/pages/audio/audio',
    'pages/component/pages/video/video',
    'pages/component/pages/swiper/swiper',
    'pages/component/pages/form/form',
    'pages/component/pages/input/input',
    'pages/component/pages/checkbox/checkbox',
    'pages/component/pages/radio/radio',
    'pages/component/pages/button/button',
    'pages/component/pages/text/text',
    'pages/component/pages/label/label',
    'pages/component/pages/picker/picker',
    'pages/component/pages/picker-view/picker-view',
    'pages/component/pages/slider/slider',
    'pages/component/pages/switch/switch',
    'pages/component/pages/textarea/textarea',
    'pages/component/pages/canvas/canvas',
    'pages/component/pages/map/map',
    'pages/component/pages/navigator/navigator',
    'pages/component/pages/redirectPage/redirectPage',
    'pages/component/pages/navigatePage/navigatePage',
    'pages/component/pages/camera/camera',

    'pages/ui/index/index',
    'pages/ui/panel/index',
    'pages/ui/basic/icon/index',
    'pages/ui/basic/button/index',
    'pages/ui/basic/color/index',
    'pages/ui/basic/typo/index',
    'pages/ui/view/noticebar/index',
    'pages/ui/view/badge/index',
    'pages/ui/view/tag/index',
    'pages/ui/view/avatar/index',
    'pages/ui/view/article/index',
    'pages/ui/view/timeline/index',
    'pages/ui/view/swiper/index',
    'pages/ui/view/load-more/index',
    'pages/ui/view/divider/index',
    'pages/ui/view/countdown/index',
    'pages/ui/view/steps/index',
    'pages/ui/view/curtain/index',
    'pages/ui/action/toast/index',
    'pages/ui/action/modal/index',
    'pages/ui/action/progress/index',
    'pages/ui/action/action-sheet/index',
    'pages/ui/action/swipe-action/index',
    'pages/ui/action/activity-indicator/index',
    'pages/ui/action/message/index',
    'pages/ui/navigation/drawer/index',
    'pages/ui/navigation/pagination/index',
    'pages/ui/navigation/tabs/index',
    'pages/ui/navigation/tabbar/index',
    'pages/ui/navigation/segmented-control/index',
    'pages/ui/navigation/navbar/index',
    'pages/ui/navigation/indexes/index',
    'pages/ui/layout/flex/index',
    'pages/ui/layout/grid/index',
    'pages/ui/layout/float-layout/index',
    'pages/ui/layout/card/index',
    'pages/ui/layout/list/index',
    'pages/ui/layout/accordion/index',
    'pages/ui/form/form/index',
    'pages/ui/form/checkbox/index',
    'pages/ui/form/input/index',
    'pages/ui/form/input-number/index',
    'pages/ui/form/radio/index',
    'pages/ui/form/textarea/index',
    'pages/ui/form/switch/index',
    'pages/ui/form/rate/index',
    'pages/ui/form/picker/index',
    'pages/ui/form/picker-view/index',
    'pages/ui/form/slider/index',
    'pages/ui/form/search-bar/index',
    'pages/ui/form/image-picker/index',
    'pages/ui/form/range/index',
    'pages/ui/advanced/calendar/index',
    'pages/ui/theme/index',

    'pages/about/about',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'Taro能力',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    backgroundColor: '#fff',
    selectedColor: '#dc0032',
    list: [
      {
        pagePath: 'pages/component/index',
        text: '组件',
        iconPath: 'assets/component/view.png',
        selectedIconPath: 'assets/component/view_red.png',
      },
      {
        pagePath: 'pages/ui/index/index',
        text: 'UI',
        iconPath: 'assets/component/view.png',
        selectedIconPath: 'assets/component/view_red.png',
      },
      {
        pagePath: 'pages/about/about',
        text: '关于',
        iconPath: 'assets/component/nav.png',
        selectedIconPath: 'assets/component/nav_red.png',
      },
    ],
  },
};
